---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: false

platforms:
- name: vagrant-openbsd-53c
  driver_config:
    box: vagrant-openbsd-53c
    box_url: http://projects.tsuntsun.net/~nabeken/boxes/vagrant-openbsd-53c.box

suites:
- name: default
  encrypted_data_bag_secret_key_path: test/integration/secret_key
  run_list:
  - recipe[nsd_test::slave]
  - recipe[minitest-handler]
